import type { Expansion } from './expansions';

/**
 * Top-off pass 01 (owner's rule, 6 Oct 2026: every article at least 1,500
 * words). Additive only: each entry appends sections to an existing article.
 */
export const TOPUP_1500_01: Expansion[] = [
  {
    slug: 'why-not-endowment-plans',
    sections: [
      {
        hHi: 'असली रिटर्न ख़ुद जाँचिए, एक शीट में',
        hEn: 'Checking the real return yourself, in one sheet',
        pHi: [
          'पिछले हिस्सों में कहा गया कि प्रभावी सालाना रिटर्न पूछिए। अगर उत्तर गोल-मोल मिले, तो उसे घर पर किसी भी स्प्रेडशीट में दस मिनट में ख़ुद निकाला जा सकता है, और यह तरीक़ा जानने लायक़ है।',
          'एक कॉलम बनाइए जिसमें हर साल की एक पंक्ति हो। हर प्रीमियम को उसी साल में माइनस संख्या के रूप में लिखिए जिसमें वह भरा गया, और परिपक्वता राशि को प्लस संख्या के रूप में उस साल में जिसमें वह मिलेगी।',
          'मनी-बैक प्लान हो तो बीच में मिलने वाली हर किश्त को भी उसके अपने साल में प्लस संख्या के रूप में लिखिए। फिर पूरे कॉलम पर स्प्रेडशीट का IRR फ़ंक्शन लगाइए। जो नतीजा आए, वही सालाना रिटर्न है।',
          'गोल संख्याओं वाला एक उदाहरण, किसी असली उत्पाद का नहीं: बीस साल तक हर साल ₹50,000, और अंत में ₹15 लाख। भरे दस लाख, मिले पंद्रह लाख — सुनने में डेढ़ गुना लगता है।',
          'इसे शीट में डालिए तो सालाना रिटर्न चार प्रतिशत से कुछ कम निकलता है। सौदा वही है, बस उसे सालाना आँकड़े में कहा गया है — और यही एकमात्र आँकड़ा है जिसे किसी जमा या दूसरे विकल्प के बगल में रखकर तुलना की जा सकती है।',
          'यह गणना पहले गारंटीड राशि पर कीजिए, और ऊँची दिखाई गई राशि पर बाद में। दोनों उत्तरों के बीच का अंतर बताता है कि आकर्षण का कितना हिस्सा उन आँकड़ों पर टिका है जिनका वादा किसी ने नहीं किया।',
        ],
        pEn: [
          'The earlier sections said to ask for the effective annual return. If the answer is vague, it can be worked out at home in ten minutes with any spreadsheet, and the method is worth knowing.',
          'Make one column with a row for each year. Enter every premium as a negative number in the year it is paid, and the maturity amount as a positive number in the year it is received.',
          'For a money-back plan, also enter each survival payout as a positive number in its own year. Then apply the spreadsheet’s IRR function to the whole column. The result is the annual return.',
          'An illustration with round numbers, not any real product: ₹50,000 a year for twenty years, and ₹15 lakh at the end. Ten lakh paid, fifteen lakh received — it sounds like half as much again.',
          'Run it through the sheet and the annual return comes to a little under four per cent. It is the same deal, described as a yearly figure, and that is the only figure that can be set beside a deposit or any other option.',
          'Do this calculation on the guaranteed amount first, and on the higher illustrated amount only second. The gap between the two answers shows how much of the attraction rests on figures nobody has promised.',
        ],
      },
      {
        hHi: 'गारंटीड और नॉन-गारंटीड: बेनिफ़िट इलस्ट्रेशन कैसे पढ़ें',
        hEn: 'Guaranteed and non-guaranteed: reading the benefit illustration',
        pHi: [
          'पॉलिसी जारी होने से पहले बीमा कंपनी एक बेनिफ़िट इलस्ट्रेशन देती है — एक तालिका जो बताती है कि किस साल क्या मिल सकता है। पूरी बिक्री में यही सबसे काम का काग़ज़ है, और अक्सर इसी पर बिना पढ़े हस्ताक्षर हो जाते हैं।',
          'इसमें दो तरह के कॉलम ढूँढिए। एक पर "गारंटीड" लिखा होता है: वह राशि अनुबंध के तहत पक्की प्रतिबद्धता है। दूसरे पर "नॉन-गारंटीड" लिखा होता है, जो आमतौर पर रिटर्न की दो अनुमानित दरों पर दिखाया जाता है।',
          'पार्टिसिपेटिंग प्लान में बोनस इसी दूसरी श्रेणी में आते हैं। वे कंपनी के फ़ंड के प्रदर्शन और भविष्य में घोषित होने वाले बोनस पर निर्भर हैं, इसलिए इलस्ट्रेशन एक संभावना है, वादा नहीं।',
          'आम ग़लती यह है कि ऊँची अनुमानित दर वाली बड़ी संख्या को ही प्लान का उत्तर मानकर याद रख लिया जाता है। वह तालिका की सबसे आशावादी पंक्ति है, और उसके पास छपी चेतावनी ठीक यही कहती है।',
          'एक व्यावहारिक आदत: गारंटीड परिपक्वता राशि और कम दर वाली अनुमानित राशि पर गोला बनाइए, और सारा सोच-विचार इन्हीं दो पर कीजिए। इनसे ऊपर जो है वह संभावित बोनस है — आए तो अच्छा, पर बीस साल के फ़ैसले का आधार नहीं।',
          'अगर बेचने वाला किसी नॉन-गारंटीड राशि को "पक्की" या "फ़िक्स्ड" बताए, तो वह बात कंपनी के लेटरहेड पर लिखित में माँगिए। अक्सर यह माँग ही मामला साफ़ कर देती है।',
        ],
        pEn: [
          'Before the policy is issued, the insurer gives a benefit illustration — a table showing what may be paid in each year. It is the most useful document in the whole sale, and it is often signed without being read.',
          'Look for two kinds of column. One is labelled guaranteed: that amount is a contractual commitment. The other is labelled non-guaranteed, and is usually shown at two assumed rates of return.',
          'In participating plans the bonuses fall into the second kind. They depend on how the insurer’s fund performs and on the bonuses it declares in future, so the illustration is a scenario, not a promise.',
          'The common mistake is to remember the larger figure from the higher assumed rate as if it were the plan’s answer. It is the most optimistic line in the table, printed beside a disclaimer that says exactly that.',
          'A practical habit: circle the guaranteed maturity figure and the lower illustrated figure, and do all your thinking on those two. Anything above them is a possible bonus — welcome if it comes, but not a basis for a twenty-year decision.',
          'If a salesperson describes a non-guaranteed figure as "assured" or "fixed", ask for that statement in writing on the insurer’s letterhead. The request usually settles the matter.',
        ],
      },
      {
        hHi: 'फ़्री-लुक अवधि और बिक्री के आम वाक्य',
        hEn: 'The free-look window and the familiar sales lines',
        pHi: [
          'इस तरह की जीवन बीमा पॉलिसी के साथ एक फ़्री-लुक अवधि मिलती है, जो पॉलिसी दस्तावेज़ में लिखी होती है। इस दौरान शर्तें ठीक न लगें तो पॉलिसी लौटाई जा सकती है। वापसी कुछ कटौतियों के बाद होती है, पर लंबी प्रतिबद्धता वहीं ख़त्म हो जाती है।',
          'जल्दबाज़ी में लिए गए फ़ैसले को सुधारने का यही सबसे सस्ता मौक़ा है। इस समय का उपयोग दस्तावेज़ को घर पर पढ़ने, ऊपर बताई रिटर्न की गणना करने, और बिक्री के समय कही गई बातों से उसका मिलान करने में कीजिए।',
          'कुछ वाक्य बार-बार सुनाई देते हैं, और हर एक पर दोबारा सोचना चाहिए। "यह FD जैसा ही है, बस उससे बेहतर": यह लंबे लॉक-इन वाला बीमा अनुबंध है, कोई जमा नहीं जिसे ज़रूरत पर तोड़ लिया जाए।',
          '"रिटर्न टैक्स-फ़्री है": कर का व्यवहार कुछ शर्तों पर निर्भर करता है, और ये शर्तें पिछले कुछ वर्षों में बदली हैं, ख़ासकर बड़े प्रीमियम वाली पॉलिसियों के लिए। दावे पर भरोसा करने के बजाय मौजूदा नियम जाँचिए।',
          '"यह ऑफ़र सिर्फ़ इसी महीने का है": जो प्लान सचमुच आपके लिए सही है, उसे किसी समय-सीमा की ज़रूरत नहीं। आज ही हस्ताक्षर करने का दबाव कल तक रुकने का कारण है।',
          'अगर पॉलिसी किसी ऐसे वादे पर बेची गई जिसका दस्तावेज़ समर्थन नहीं करता, तो पहले बीमा कंपनी के शिकायत विभाग में लिखित शिकायत कीजिए। वहाँ समाधान न हो तो नियामक की शिकायत व्यवस्था और बीमा लोकपाल अगले क़दम हैं।',
        ],
        pEn: [
          'Life policies of this kind come with a free-look period, stated in the policy document, during which the policy can be returned if its terms do not suit. The refund is made after certain deductions, but the long commitment ends there.',
          'That window is the cheapest moment to correct a hasty decision. Use it to read the document at home, run the return calculation above, and compare what is written with what was said at the time of sale.',
          'Some lines are heard again and again, and each deserves a second look. "This is just like a fixed deposit, only better": it is an insurance contract with a long lock-in, not a deposit that can be broken when needed.',
          '"The returns are tax-free": the tax treatment depends on conditions, and those conditions have changed in recent years, particularly for policies with larger premiums. Check the current rules rather than relying on the claim.',
          '"This offer is only for this month": a plan that genuinely suits you does not need a deadline. Pressure to sign today is a reason to wait until tomorrow.',
          'If a policy was sold on a promise that the document does not support, complain first in writing to the insurer’s grievance cell. If that does not resolve it, the regulator’s grievance system and the Insurance Ombudsman are the next steps.',
        ],
      },
    ],
  },
  {
    slug: 'advance-tax-basics',
    sections: [
      {
        hHi: 'एक उदाहरण: जब साल के बीच अनुमान बदल जाए',
        hEn: 'A worked example: when the estimate changes mid-year',
        pHi: [
          'एक उदाहरण से यह जुड़ती जाने वाली व्यवस्था साफ़ हो जाती है। मान लीजिए मीरा एक फ़्रीलांस डिज़ाइनर हैं, जिनका कर काटने वाला कोई नियोक्ता नहीं है। संख्याएँ गोल हैं और केवल समझाने के लिए हैं, किसी साल की असली दरें नहीं।',
          'जून की शुरुआत में वे अनुमान लगाती हैं कि ग्राहकों द्वारा स्रोत पर काटे गए कर के बाद साल का कर ₹60,000 होगा। पहली तारीख़ से पहले वे इस राशि का वह हिस्सा जमा कर देती हैं जो उस तारीख़ के लिए तय है।',
          'अगस्त में एक बड़ा प्रोजेक्ट आ जाता है। हिसाब का पन्ना दोबारा बनाने पर पता चलता है कि अब साल का कर लगभग ₹1,00,000 होगा। अगली किश्त पुराने आँकड़े में थोड़ा जोड़कर तय नहीं की जाती।',
          'वे नए आँकड़े ₹1,00,000 पर दूसरी तारीख़ तक देय कुल हिस्सा निकालती हैं, उसमें से पहले से जमा राशि घटाती हैं, और अंतर जमा कर देती हैं। यह एक भुगतान नए अनुमान को भी पूरा करता है और पिछली कमी को भी भर देता है।',
          'पहली अवधि के लिए फिर भी थोड़ा ब्याज लग सकता है, क्योंकि उसकी गणना साल के अंतिम कर के आधार पर होती है — पर वह केवल एक छोटे अंतराल का होता है। अगर वे रिटर्न भरने तक रुकतीं, तो पूरे अंतर पर कई महीनों का ब्याज चढ़ता।',
          'अगर बाद में साल अनुमान से धीमा निकले, तो कुछ नहीं बिगड़ता। ज़्यादा जमा किया गया कर रिटर्न की प्रोसेसिंग के बाद रिफ़ंड होकर लौट आता है — हालाँकि तब तक पैसा अटका रहता है, इसलिए खुले हाथ वाले अनुमान से सावधान अनुमान बेहतर है।',
        ],
        pEn: [
          'An example makes the cumulative structure clear. Take Meera, a freelance designer with no employer deducting tax for her. The figures are round and purely illustrative, not any particular year’s actual rates.',
          'In early June she estimates that her tax for the year, after the tax her clients deduct at source, will be ₹60,000. Before the first date she deposits the share of that figure prescribed for that date.',
          'In August a large project comes in. Rebuilding her one-page working, she finds the year’s tax is now likely to be ₹1,00,000. The next instalment is not worked out as the old figure plus a little extra.',
          'She calculates the cumulative share due by the second date on the new figure of ₹1,00,000, subtracts what she has already paid, and deposits the difference. That single payment covers the new estimate and closes the earlier gap.',
          'A small interest charge may still arise for the first period, because it is worked out against the year’s final tax — but it covers only a short gap. Had she waited until filing the return, interest would have run on the whole difference for many months.',
          'If the year then turns out quieter than expected, nothing is lost. Tax paid in excess comes back as a refund once the return is processed — though the money is locked up until then, which is why a careful estimate beats a generous one.',
        ],
      },
      {
        hHi: 'सही तरीक़े से भुगतान: वे बारीकियाँ जो परेशानी देती हैं',
        hEn: 'Paying it correctly: the details that cause trouble',
        pHi: [
          'अग्रिम कर आयकर ई-फ़ाइलिंग पोर्टल या अपने बैंक की नेट बैंकिंग से, कर भुगतान वाले चालान के ज़रिए ऑनलाइन जमा होता है। प्रक्रिया कुछ मिनट की है, पर फ़ॉर्म के दो चुनाव तय करते हैं कि भुगतान सही जगह पहुँचेगा या नहीं।',
          'पहला है निर्धारण वर्ष (असेसमेंट ईयर)। किसी वित्त वर्ष के कर का निर्धारण अगले वर्ष होता है, इसलिए वह निर्धारण वर्ष चुनना है जो उस वर्ष के बाद आता है जिसमें आय कमाई जा रही है। आदतवश चालू वर्ष चुन लेना सबसे आम ग़लती है।',
          'दूसरा है भुगतान का प्रकार। साल के दौरान "अग्रिम कर" चुनिए। "सेल्फ़-असेसमेंट टैक्स" अलग श्रेणी है, जो साल ख़त्म होने के बाद और रिटर्न भरने से पहले बचे हुए कर के लिए होती है।',
          'भुगतान से पहले स्क्रीन पर अपना PAN ज़रूर जाँचिए। ग़लत PAN पर जमा हुई राशि खोती नहीं, पर उसे सही करवाने में कुछ सेकंड की जाँच से कहीं ज़्यादा समय लगता है।',
          'चालान की रसीद उसकी पहचान संख्या और तारीख़ के साथ सँभालकर रखिए। रिटर्न भरते समय ये विवरण "जमा किए गए कर" वाले हिस्से में भरे जाते हैं, और इन्हें बैंक के रिकॉर्ड से हूबहू मेल खाना चाहिए।',
          'अगर ग़लती हो चुकी है — ग़लत वर्ष या ग़लत प्रकार — तो उसे सुधरवाने का अनुरोध किया जा सकता है, पोर्टल की मौजूदा प्रक्रिया से या कर-निर्धारण अधिकारी के ज़रिए, और कुछ सुधारों की समय-सीमा भी होती है। रसीद हाथ में रखकर जल्दी क़दम उठाइए।',
        ],
        pEn: [
          'Advance tax is paid online through the income tax e-filing portal or your bank’s net banking, using the challan for tax payments. The process takes a few minutes, but two choices on the form decide whether the payment lands in the right place.',
          'The first is the assessment year. Tax for a financial year is assessed in the following year, so the assessment year to choose is the one after the year in which the income is being earned. Selecting the current year out of habit is the commonest error.',
          'The second is the type of payment. During the year, choose advance tax. Self-assessment tax is a different category, meant for tax still due after the year has ended and before the return is filed.',
          'Check your PAN on the screen before paying. A payment credited to the wrong PAN is not lost, but getting it corrected takes far longer than the few seconds a check takes.',
          'Save the challan receipt with its identification number and date. While filing the return these details go into the taxes-paid section, and they must match the bank’s record exactly.',
          'If a mistake has already happened — the wrong year or the wrong type — a correction can be requested, either through the portal’s current procedure or through the assessing officer, and some corrections have time limits. Act early, with the receipt in hand.',
        ],
      },
      {
        hHi: 'चार स्थितियाँ जिन पर अलग से ध्यान चाहिए',
        hEn: 'Four situations that need a closer look',
        pHi: [
          'चार स्थितियाँ इतनी बार सामने आती हैं कि उन पर अलग से बात करना ज़रूरी है, क्योंकि इनमें चार तारीख़ों की सामान्य लय पूरी तरह फ़िट नहीं बैठती।',
          'पहली है एक बार का लाभ — साल के बीच में मकान, शेयर या फ़ंड की यूनिटें बेचना। ऐसी आय का अनुमान साल की शुरुआत में लगाया ही नहीं जा सकता था, और नियम आमतौर पर इसे इसी रूप में देखते हैं, बशर्ते उस पर कर उसके बाद बची किश्तों में चुका दिया जाए। इसलिए बिक्री के ठीक बाद वाली किश्त में क़दम उठाइए, साल के अंत में नहीं।',
          'दूसरी है वह छोटा व्यवसायी या पेशेवर जिसने अनुमानित आय (प्रिज़म्प्टिव) वाली सरल कर योजना चुनी है। नियम ऐसे करदाताओं को पूरा अग्रिम कर अंतिम तारीख़ तक एक ही किश्त में चुकाने की अनुमति देते हैं। इस पर भरोसा करने से पहले पुष्टि कर लीजिए कि यह विकल्प आप पर लागू होता है।',
          'तीसरी है वह वेतनभोगी व्यक्ति जो साल के बीच नौकरी बदलता है। हर नियोक्ता ऐसे कर काटता है मानो उसका वेतन ही अकेली आय हो, जबकि दोनों को मिलाकर आय अक्सर ऊँचे स्लैब में पहुँच जाती है। जब तक नए नियोक्ता को पिछले वेतन की जानकारी न दी जाए या अंतर अग्रिम कर के रूप में न चुकाया जाए, यह कमी साल के अंत में सामने आती है।',
          'चौथी है जमा पर मिलने वाला ब्याज, जिस पर कर आपके अपने स्लैब से कम दर पर कटता है। कटौती देखकर लगता है कि मामला निपट गया, पर बाक़ी अंतर फिर भी देय रहता है।',
          'चारों में इलाज एक ही है — ऊपर बताया गया तिमाही वाला पन्ना, जिसमें संबंधित मद के लिए एक अतिरिक्त पंक्ति हो। जहाँ रक़में बड़ी हों, वहाँ किसी योग्य कर सलाहकार से जाँच करवाना सही ख़र्च है।',
        ],
        pEn: [
          'Four situations come up often enough to deserve a separate word, because in each the ordinary rhythm of four dates does not quite fit.',
          'The first is a one-time gain — selling property, shares or fund units part-way through the year. Such income could not have been foreseen at the start, and the rules generally treat it accordingly, provided the tax on it is paid in the instalments that remain after it arises. So act in the instalment immediately after the sale, not at year-end.',
          'The second is the small business owner or professional who has opted for the simplified, presumptive scheme of taxation. The rules allow such taxpayers to pay their whole advance tax in a single instalment by the last date. Confirm that the option applies to you before relying on it.',
          'The third is the salaried person who changes jobs during the year. Each employer deducts tax as if its salary were the only income, while the combined income often falls into a higher bracket. Unless the new employer is told about the earlier salary, or the difference is paid as advance tax, the gap surfaces at year-end.',
          'The fourth is interest on deposits where tax is deducted at a rate lower than your own bracket. The deduction makes the matter feel settled, but the difference remains payable.',
          'In all four the remedy is the same quarterly page described above, with one extra line for the item in question. Where the amounts are large, a review by a qualified tax adviser is money well spent.',
        ],
      },
    ],
  },
  {
    slug: 'motor-insurance-basics',
    sections: [
      {
        hHi: 'क्लेम असल में कैसे निपटता है: कैशलेस या रीइम्बर्समेंट',
        hEn: 'How a claim is actually settled: cashless or reimbursement',
        pHi: [
          'अधिकांश लोग अपनी गाड़ी के नुक़सान (ओन-डैमेज) वाले क्लेम की प्रक्रिया तभी सीखते हैं जब वे क्लेम कर रहे होते हैं। क्रम पहले से पता हो तो तनाव भी काफ़ी घटता है और अधिकांश विवाद भी।',
          'कैशलेस क्लेम में गाड़ी बीमा कंपनी के नेटवर्क वाले गैराज में जाती है। सर्वेयर नुक़सान की जाँच करता है, गैराज अनुमान (एस्टिमेट) बनाता है, कंपनी उसे मंज़ूर करती है, और अपना हिस्सा सीधे गैराज को चुकाती है।',
          'कैशलेस का मतलब यह नहीं कि आपको कुछ नहीं देना। डिडक्टिबल, ज़ीरो-डेप्रिसिएशन कवर न हो तो पुर्ज़ों पर कटा मूल्य-ह्रास, और जो कुछ सर्वेयर मंज़ूर न करे — ये सब गाड़ी लेते समय आपकी जेब से ही जाते हैं।',
          'रीइम्बर्समेंट क्लेम में आप अपनी पसंद के गैराज में मरम्मत करवाते हैं, बिल ख़ुद चुकाते हैं, और फिर बिल, रसीदें और दस्तावेज़ जमा करके भुगतान वापस माँगते हैं। इसमें आज़ादी ज़्यादा है, पर काग़ज़ी काम और धैर्य भी ज़्यादा चाहिए।',
          'दो आदतें दोनों रास्तों को आसान बनाती हैं। सर्वेयर की जाँच से पहले मरम्मत शुरू मत होने दीजिए, और गैराज से मदवार अनुमान माँगिए जिसमें साफ़ लिखा हो कि कौन-से पुर्ज़े बदले जा रहे हैं और कौन-से ठीक किए जा रहे हैं।',
          'पॉलिसी चुनने से पहले देखिए कि आपके घर और दफ़्तर के पास कौन-से गैराज कंपनी के नेटवर्क में हैं। नेटवर्क की लंबी सूची किस काम की, अगर सबसे पास का कैशलेस गैराज दो घंटे दूर हो।',
        ],
        pEn: [
          'Most people learn how an own-damage claim works only while they are making one. Knowing the sequence in advance removes much of the stress and most of the disputes.',
          'In a cashless claim the vehicle goes to a garage in the insurer’s network. A surveyor inspects the damage, the garage prepares an estimate, the insurer approves it, and the insurer pays its share directly to the garage.',
          'Cashless does not mean you pay nothing. The deductible, the depreciation on parts if you have no zero-depreciation cover, and anything the surveyor does not approve still come out of your pocket when you collect the vehicle.',
          'In a reimbursement claim you use a garage of your choice, pay the bill yourself, and then submit the bills, receipts and documents to be repaid. It allows more freedom but needs more paperwork and more patience.',
          'Two habits make either route smoother. Do not let repairs begin before the surveyor has inspected the vehicle, and ask the garage for an itemised estimate showing clearly which parts are being replaced and which repaired.',
          'Before choosing a policy, check which garages near your home and workplace are in the insurer’s network. A long network list helps little if the nearest cashless garage is two hours away.',
        ],
      },
      {
        hHi: 'क्लेम क्यों ख़ारिज होते हैं, और हर कारण से कैसे बचें',
        hEn: 'Why claims get rejected, and how to avoid each reason',
        pHi: [
          'ख़ारिज होने वाले अधिकांश क्लेम कुछ गिने-चुने कारणों से गिरते हैं, और लगभग सभी को कुछ होने से पहले ही रोका जा सकता है।',
          'पहला कारण चालक से जुड़ा है: वैध लाइसेंस न होना, या किसी दूसरी श्रेणी की गाड़ी का लाइसेंस होना। उपाय सीधा है — गाड़ी चलाने वाले हर व्यक्ति के पास सही लाइसेंस हो, उस परिजन के पास भी जो कभी-कभार ही चलाता है।',
          'दूसरा है शराब या नशे की हालत में गाड़ी चलाना। पॉलिसियाँ इसे कवर नहीं करतीं, और बाद का कोई भी काग़ज़ इसे ठीक नहीं कर सकता।',
          'तीसरा है ऐसा उपयोग जो पॉलिसी से मेल न खाए — जैसे निजी पंजीकरण वाली कार में किराया लेकर सवारी या सामान ढोना। अगर गाड़ी से कमाई होती है, तो पॉलिसी में यह दर्ज होना चाहिए।',
          'चौथा है बिना बताया गया बदलाव: CNG किट, बदला हुआ इंजन, या कोई बड़ा परिवर्तन जो पंजीकरण और पॉलिसी में दर्ज न हो। हर बदलाव का एंडोर्समेंट उसी समय करवाइए, दुर्घटना के बाद नहीं।',
          'पाँचवाँ है वह कमी जिसे पॉलिसी कभी कवर करती ही नहीं थी: सामान्य घिसावट, मशीनी ख़राबी, या टूटी गाड़ी को चलाते रहने से हुआ आगे का नुक़सान। अपवादों वाला पन्ना एक बार पढ़ लीजिए; वह लोगों की सोच से छोटा होता है।',
        ],
        pEn: [
          'Most rejected claims fail for a handful of reasons, and nearly all of them can be prevented before anything happens.',
          'The first concerns the driver: no valid licence, or a licence for a different class of vehicle. The fix is simply to make sure everyone who drives the vehicle holds the right licence — including the family member who drives only occasionally.',
          'The second is driving under the influence of alcohol or drugs. Policies exclude it, and no paperwork afterwards can repair that.',
          'The third is use that does not match the policy — a privately registered car used to carry paying passengers or goods, for example. If the vehicle earns money, the policy has to say so.',
          'The fourth is an undeclared change: a CNG kit, a replacement engine, or a major modification not recorded in the registration and the policy. Get each change endorsed when it is made, not after an accident.',
          'The fifth is a gap the policy never covered: ordinary wear and tear, mechanical breakdown, or further damage caused by continuing to drive a damaged vehicle. Read the exclusions page once; it is shorter than people expect.',
        ],
      },
      {
        hHi: 'कई साल का थर्ड-पार्टी कवर, और गाड़ी बेचते समय',
        hEn: 'Multi-year third-party cover, and selling a vehicle',
        pHi: [
          'नई कारें और दोपहिया अब कई साल चलने वाले थर्ड-पार्टी कवर के साथ बिकते हैं। इसके उलट ओन-डैमेज कवर आमतौर पर एक-एक साल के लिए लिया जाता है, और उसे अलग से भी ख़रीदा जा सकता है।',
          'इससे रिन्यूअल का अर्थ बदल जाता है। शुरुआती सालों में केवल ओन-डैमेज वाला हिस्सा देय हो सकता है, और शर्तें बेहतर हों तो उसे किसी दूसरी कंपनी से भी लिया जा सकता है। दोनों की समाप्ति तिथियाँ जाँचिए — वे अक्सर एक नहीं होतीं।',
          'उल्टी ग़लती भी होती है: थर्ड-पार्टी कवर चल रहा है, इसलिए गाड़ी को "बीमित" मानकर ओन-डैमेज कवर समाप्त हो जाने दिया जाता है। गाड़ी बीमित तो है — पर केवल दूसरों के नुक़सान के लिए।',
          'गाड़ी बेचते समय बीमा भी उसके साथ जाना चाहिए। पंजीकरण ट्रांसफ़र होने के बाद ख़रीदार को जल्द से जल्द, कंपनी द्वारा माँगे गए दस्तावेज़ों के साथ, पॉलिसी अपने नाम ट्रांसफ़र करवाने का आवेदन करना चाहिए।',
          'बेचने वाले के रूप में बिक्री की तारीख़ और पंजीकरण ट्रांसफ़र का सबूत सँभालकर रखिए। जब तक पंजीकरण नहीं बदलता, गाड़ी से जुड़ा कोई दावा आप तक भी पहुँच सकता है।',
          'और पहले बताया गया नो-क्लेम बोनस याद रखिए: वह आपका है, गाड़ी का नहीं। चाबी सौंपने से पहले उसका प्रमाणपत्र ले लीजिए, ताकि छूट आपकी अगली पॉलिसी में जा सके।',
        ],
        pEn: [
          'New cars and two-wheelers are now sold with third-party cover that runs for several years. Own-damage cover, by contrast, is usually bought one year at a time, and it can be bought separately.',
          'This changes what renewal means. In the early years only the own-damage part may be due, and it can be bought from a different insurer if the terms are better. Check both expiry dates — they are often not the same.',
          'The opposite mistake happens too: somebody lets own-damage cover lapse, thinking the vehicle is "insured" because third-party cover is still running. It is insured — but only for damage to others.',
          'When a vehicle is sold, the insurance has to move with it. Once the registration has been transferred, the buyer should apply promptly to have the policy transferred into their name, with the documents the insurer asks for.',
          'As the seller, keep proof of the date of sale and of the registration transfer. Until the registration changes, a claim arising from the vehicle can still come looking for you.',
          'And remember the no-claim bonus mentioned earlier: it belongs to you, not to the vehicle. Ask for the certificate before handing over the keys, so the discount can go onto your next policy.',
        ],
      },
    ],
  },
  {
    slug: 'minimum-due-trap',
    sections: [
      {
        hHi: 'न्यूनतम चुकाने का आपकी क्रेडिट रिपोर्ट पर असर',
        hEn: 'What paying the minimum does to your credit report',
        pHi: [
          'एक आम धारणा यह है कि न्यूनतम राशि समय पर चुकाने से क्रेडिट रिकॉर्ड साफ़ रहता है। यह आंशिक रूप से सही है, और जो हिस्सा सही नहीं है, नुक़सान वहीं होता है।',
          'देय तिथि तक कम-से-कम न्यूनतम राशि चुकाना आमतौर पर समय पर भुगतान माना जाता है। न्यूनतम से कम चुकाना, या देर से चुकाना, अलग बात है: लेट फ़ीस लगती है और खाता बकाया (ओवरड्यू) के रूप में रिपोर्ट हो सकता है।',
          'पर रिपोर्ट केवल यह नहीं दिखाती कि आपने भुगतान किया या नहीं। वह यह भी दिखाती है कि आपकी सीमा का कितना हिस्सा इस्तेमाल में है। केवल न्यूनतम चुकाने से जो शेष हर महीने बढ़ता है, वह इस हिस्से को महीने-दर-महीने ऊपर ले जाता है।',
          'रिपोर्ट पढ़ने वाले ऋणदाता एक महीना नहीं, एक पैटर्न देखते हैं: ऊँचा उपयोग, आगे खिसकता शेष, वही कार्ड हमेशा अपनी सीमा के पास। यह पैटर्न अगला ऋण महँगा या मुश्किल बना सकता है, भले ही एक भी भुगतान न चूका हो।',
          'इसलिए "मैंने कभी डिफ़ॉल्ट नहीं किया" और "मेरा क्रेडिट स्वस्थ है" एक ही बात नहीं हैं। पहली बात देय तिथियों के बारे में है; दूसरी इस बारे में भी कि आप जितना उधार ले सकते हैं, उसकी तुलना में कितना बकाया है।',
          'क्रेडिट ब्यूरो साल में एक बार मुफ़्त रिपोर्ट देते हैं; अपनी रिपोर्ट ज़रूर देखिए। उपयोग का आँकड़ा ख़ुद देख लेने से अक्सर वह इनकार समझ में आ जाता है जिसे किसी ऋणदाता ने समझाने की ज़हमत नहीं उठाई।',
        ],
        pEn: [
          'A common belief is that paying the minimum on time keeps the credit record clean. That is partly true, and the part that is not true is where the damage happens.',
          'Paying at least the minimum by the due date is generally treated as an on-time payment. Paying less than the minimum, or paying late, is different: a late fee applies and the account can be reported as overdue.',
          'But the report shows more than whether you paid. It also shows how much of your limit is in use. A balance that keeps growing because only the minimum is paid pushes that share up, month after month.',
          'Lenders reading the report see a pattern, not a single month: high usage, balances carried forward, the same card always close to its limit. That pattern can make the next loan costlier or harder to get, even without a single missed payment.',
          'So "I have never defaulted" and "my credit is healthy" are not the same statement. The first is about due dates; the second is also about how much you owe compared with how much you are able to borrow.',
          'Credit bureaus provide a free report once a year; use it. Seeing the utilisation figure for yourself often explains a rejection that no lender took the trouble to explain.',
        ],
      },
      {
        hHi: 'किश्तें, ऋण या बैलेंस ट्रांसफ़र: बाहर निकलने का रास्ता चुनना',
        hEn: 'Instalments, a loan or a balance transfer: choosing the way out',
        pHi: [
          'जब शेष इतना बड़ा हो जाए कि एक-दो महीने में न चुक सके, तो आमतौर पर तीन रास्ते सामने रखे जाते हैं। हर एक मदद कर सकता है, और ग़लत कारण से चुना जाए तो हर एक हालत बिगाड़ भी सकता है।',
          'उसी कार्ड कंपनी के साथ शेष को किश्तों में बदलवाना सबसे सरल है। तीन बातें पूछिए: ब्याज दर, प्रोसेसिंग फ़ीस, और क्या बदली गई राशि आपकी सीमा का हिस्सा रोककर रखेगी। ब्याज और शुल्क पर टैक्स भी जुड़ता है, इसलिए कुल लागत की तुलना कीजिए।',
          'कार्ड चुकाने के लिए पर्सनल लोन तब काम कर सकता है जब उसकी दर साफ़ तौर पर कम हो और अवधि छोटी। ख़तरा व्यवहार का है: कार्ड अब ख़ाली है, और अगर ख़र्च फिर शुरू हो गया तो हाथ में ऋण भी होगा और कार्ड का नया शेष भी।',
          'कम शुरुआती दर पर किसी दूसरे कार्ड में बैलेंस ट्रांसफ़र तभी काम का है जब पूरी राशि उसी अवधि में चुकाई जा सके। अवधि ख़त्म होते ही सामान्य कार्ड दर लौट आती है, और शुरुआत में आमतौर पर एक ट्रांसफ़र शुल्क भी लगता है।',
          'फ़ैसले का एक सरल तरीक़ा: वह रास्ता चुनिए जिसकी कुल लागत सबसे कम हो और जिसकी समाप्ति तिथि तय हो — इस शर्त के साथ कि क़र्ज़ ख़त्म होने तक पुराना कार्ड किनारे रहेगा। इस शर्त के बिना हर रास्ता वहीं लौट आता है जहाँ से चले थे।',
          'हर प्रस्ताव की शर्तें लिखित में लीजिए — मोस्ट इम्पॉर्टेंट टर्म्स एंड कंडीशंस (MITC) दस्तावेज़ और किश्तों की सूची — और फ़ोन पर हाँ कहने से पहले उन्हें घर पर पढ़िए।',
        ],
        pEn: [
          'Once the balance is too large to clear in a month or two, three routes are usually offered. Each can help, and each can make things worse if it is chosen for the wrong reason.',
          'Converting the balance into instalments with the same card company is the simplest. Ask three things: the rate, the processing fee, and whether the converted amount keeps part of your limit blocked. Tax is also added to interest and fees, so compare the full cost.',
          'A personal loan to clear the card can work if its rate is clearly lower and its term is short. The danger is behavioural: the card is now empty, and if spending resumes you end up with both a loan and a fresh card balance.',
          'A balance transfer to another card at a low introductory rate helps only if the whole amount can be repaid within that period. When the period ends the ordinary card rate returns, and a transfer fee is usually charged at the start.',
          'A simple way to decide: take the route with the lowest total cost and a fixed end date — on the condition that the old card is put away until the debt is gone. Without that condition, every route leads back to where you began.',
          'Get the terms of each offer in writing — the Most Important Terms and Conditions document and the instalment schedule — and read them at home before agreeing to anything on the phone.',
        ],
      },
      {
        hHi: 'अगर इस महीने न्यूनतम भी न चुक सके',
        hEn: 'If even the minimum cannot be paid this month',
        pHi: [
          'कभी-कभी आय रुक जाती है और न्यूनतम राशि भी पहुँच से बाहर हो जाती है। सबसे बुरी प्रतिक्रिया चुप्पी है; उसके बाद सबसे बुरी है कार्ड भरने के लिए किसी ऐप से कहीं ज़्यादा महँगा उधार लेना।',
          'देय तिथि से पहले कार्ड कंपनी को फ़ोन कीजिए, बाद में नहीं। स्थिति साफ़-साफ़ बताइए और पूछिए कि कौन-से विकल्प हैं — थोड़े समय की व्यवस्था, किश्तों की नई योजना, या कुछ शुल्कों में छूट। तारीख़, बात करने वाले का नाम और जो प्रस्ताव मिला, लिख लीजिए।',
          'अगर "सेटलमेंट" का प्रस्ताव आए — पूरी राशि से कम चुकाकर खाता बंद करना — तो उसकी क़ीमत समझिए। तब खाता आमतौर पर "बंद" नहीं, "सेटल्ड" के रूप में रिपोर्ट होता है, और ऋणदाता यह शब्द वर्षों तक पढ़ते हैं।',
          'वसूली के दौरान आपके अधिकार भी हैं। रिज़र्व बैंक के नियम कहते हैं कि ऋणदाता और उनके एजेंट उधारकर्ता से सम्मानजनक व्यवहार करें — धमकी, गाली-गलौज या बेवक़्त फ़ोन के बिना।',
          'अगर यह सीमा टूटे, तो बैंक के शिकायत अधिकारी को लिखित शिकायत कीजिए। तय समय में संतोषजनक उत्तर न मिले, तो रिज़र्व बैंक की लोकपाल योजना में ऑनलाइन शिकायत की जा सकती है।',
          'और अगर एक से ज़्यादा क़र्ज़ हैं, तो कई बैंकों द्वारा चलाए जाने वाले वित्तीय साक्षरता और क्रेडिट परामर्श केंद्रों में, या किसी योग्य सलाहकार से बात करना उस स्थिति में व्यवस्था ला सकता है जो अकेले सँभालना असंभव लगती है।',
        ],
        pEn: [
          'Sometimes income stops and even the minimum is out of reach. The worst response is silence; the second worst is borrowing from an app at a far higher cost to pay the card.',
          'Call the card company before the due date, not after it. Explain the situation plainly and ask what options exist — a short-term arrangement, a restructured instalment plan, or a waiver of some charges. Note the date, the name of the person and what was offered.',
          'If a "settlement" is offered — paying less than the full amount to close the account — understand its cost. The account is then usually reported as settled rather than closed, and lenders read that word for years.',
          'You also have rights during recovery. Rules issued by the Reserve Bank require lenders and their agents to treat borrowers with dignity — without threats, abuse or calls at unreasonable hours.',
          'If that line is crossed, complain in writing to the bank’s grievance officer. If no satisfactory reply arrives within the stated time, the Reserve Bank’s Ombudsman scheme accepts complaints online.',
          'And if more than one debt is involved, a conversation at one of the financial literacy and credit counselling centres that many banks run, or with a qualified adviser, can bring order to a situation that feels unmanageable alone.',
        ],
      },
    ],
  },
  {
    slug: 'personal-loan-emi-basics',
    sections: [
      {
        hHi: 'एक ऋण, संख्याओं के साथ',
        hEn: 'One loan, worked through with numbers',
        pHi: [
          'ऊपर की बातें संख्याओं के साथ ज़्यादा साफ़ महसूस होती हैं। यहाँ दी गई संख्याएँ केवल समझाने के लिए हैं, किसी ऋणदाता की दर नहीं।',
          'मान लीजिए ₹3,00,000 का ऋण, घटते शेष (रिड्यूसिंग बैलेंस) पर 14 प्रतिशत सालाना दर से। तीन साल की अवधि में किश्त लगभग ₹10,250 बनती है और कुल चुकाई गई राशि लगभग ₹3,69,000 — यानी क़रीब ₹69,000 ब्याज।',
          'इसी ऋण को पाँच साल तक खींच दीजिए तो किश्त घटकर लगभग ₹6,980 रह जाती है, जो काफ़ी हल्की लगती है। पर कुल चुकाई गई राशि बढ़कर लगभग ₹4,19,000 हो जाती है, यानी ब्याज लगभग ₹1,19,000 — छोटी किश्त के आराम के बदले क़रीब ₹50,000 ज़्यादा।',
          'अब फ़्लैट दर की तुलना। उसी ₹3,00,000 का तीन साल का ऋण अगर "फ़्लैट" 10 प्रतिशत पर दिया जाए, तो तीनों सालों में हर साल ₹30,000 ब्याज लगता है — कुल ₹90,000 — और किश्त लगभग ₹10,830 बनती है।',
          'वह फ़्लैट 10 प्रतिशत घटते शेष के हिसाब से लगभग 18 प्रतिशत बैठता है — 14 प्रतिशत वाले प्रस्ताव से ज़्यादा, जबकि उसकी विज्ञापित संख्या छोटी है। यही कारण है कि तुलना का एकमात्र उचित आधार सालाना प्रतिशत दर (APR) है।',
          'कोई भी ऑनलाइन लोन कैलकुलेटर ये संख्याएँ एक मिनट में दोबारा निकाल देगा। हस्ताक्षर से पहले अपना प्रस्ताव उसमें डालिए, और किश्त नहीं, कुल चुकाई जाने वाली राशि देखिए।',
        ],
        pEn: [
          'The points above are easier to feel with numbers. The figures here are illustrative, chosen to show the mechanics, and are not a quote of any lender’s rate.',
          'Take a loan of ₹3,00,000 at 14 per cent a year on a reducing balance. Over three years the instalment is about ₹10,250, and the total repaid is roughly ₹3,69,000 — about ₹69,000 in interest.',
          'Stretch the same loan to five years and the instalment falls to about ₹6,980, which feels much lighter. But the total repaid rises to roughly ₹4,19,000, so the interest climbs to about ₹1,19,000 — some ₹50,000 more for the comfort of a smaller instalment.',
          'Now the flat-rate comparison. A three-year loan of the same ₹3,00,000 offered at a "flat" 10 per cent charges ₹30,000 of interest in each of the three years, ₹90,000 in all, with an instalment of about ₹10,830.',
          'That flat 10 per cent works out to roughly 18 per cent on a reducing balance — more than the 14 per cent offer, even though its headline number is smaller. This is exactly why the annual percentage rate is the only fair basis for comparison.',
          'Any online loan calculator will reproduce these figures in a minute. Put your own offer into one before signing, and look at the total repaid rather than the instalment.',
        ],
      },
      {
        hHi: 'इंस्टेंट लोन ऐप: ऋण से पहले ऋणदाता की जाँच',
        hEn: 'Instant loan apps: checking the lender before the loan',
        pHi: [
          'मिनटों में फ़ोन पर मंज़ूर होने वाले ऋण अब आम हैं, और इनमें से कई विधिवत विनियमित ऋणदाताओं के होते हैं। पर इनके साथ ऐसे ऐप भी चलते हैं जो किसी नियमन में नहीं आते, और यह अंतर गति से कहीं ज़्यादा मायने रखता है।',
          'पहले यह जाँचिए कि असल में ऋण कौन दे रहा है। ऐप को उस बैंक या गैर-बैंकिंग वित्त कंपनी (NBFC) का नाम बताना चाहिए जो ऋण के पीछे है, और वह कंपनी रिज़र्व बैंक की विनियमित संस्थाओं की सार्वजनिक सूचियों में दिखनी चाहिए। जो ऐप अपने ऋणदाता का नाम न बता सके, उससे उधार नहीं लेना चाहिए।',
          'दूसरा, विनियमित ऋणदाता को हस्ताक्षर से पहले एक की फ़ैक्ट स्टेटमेंट (KFS) देना होता है, जिसमें सालाना प्रतिशत दर, सारे शुल्क और भुगतान की सूची एक मानक प्रारूप में लिखी हो। अगर ऐसा कोई विवरण सामने न आए, तो वहीं रुक जाइए।',
          'तीसरा, देखिए कि ऐप क्या-क्या माँग रहा है। आपके कॉन्टैक्ट, फ़ोटो गैलरी या मैसेज तक पहुँच की माँग का ऋण के आकलन से कोई लेना-देना नहीं, और ऐसी पहुँच का उपयोग उत्पीड़न के लिए हुआ है।',
          'चौथा, पैसा सीधे आपके अपने बैंक खाते में आना चाहिए और किश्तें सीधे ऋणदाता को जानी चाहिए — किसी निजी खाते या किसी तीसरे के वॉलेट में नहीं।',
          'अगर कुछ ग़लत हो चुका है — धमकियाँ, आपके कॉन्टैक्ट्स को संदेश, ऐसे शुल्क जो कभी बताए नहीं गए — तो सरकार के साइबर अपराध पोर्टल या हेल्पलाइन पर रिपोर्ट कीजिए, और ऋणदाता के शिकायत अधिकारी तथा नियामक की शिकायत व्यवस्था में शिकायत दर्ज कीजिए।',
        ],
        pEn: [
          'Loans approved on a phone within minutes are now common, and many come from properly regulated lenders. Alongside them operate apps that are not regulated at all, and that difference matters far more than the speed.',
          'First, check who is actually lending. The app should name the bank or non-banking finance company behind the loan, and that company should appear in the Reserve Bank’s public lists of regulated entities. An app that cannot name its lender is not one to borrow from.',
          'Second, a regulated lender has to give you a Key Fact Statement before you sign, setting out the annual percentage rate, all the charges and the repayment schedule in a standard format. If no such statement appears, stop there.',
          'Third, look at what the app asks for. A request for access to your contacts, photo gallery or messages has nothing to do with assessing a loan, and such access has been used for harassment.',
          'Fourth, the money should arrive in your own bank account, and repayments should go directly to the lender — not to a personal account or a third party’s wallet.',
          'If something has already gone wrong — threats, messages to your contacts, charges that were never disclosed — report it on the government’s cybercrime portal or helpline, and complain to the lender’s grievance officer and through the regulator’s complaint system.',
        ],
      },
      {
        hHi: 'क्रेडिट को नुक़सान पहुँचाए बिना आवेदन, और गारंटर का सवाल',
        hEn: 'Applying without hurting your credit, and the guarantor question',
        pHi: [
          'हर औपचारिक ऋण आवेदन से आमतौर पर आपकी क्रेडिट रिपोर्ट पर एक पूछताछ (इन्क्वायरी) दर्ज होती है। कुछ पूछताछ सामान्य हैं; कम समय में बहुत सारी पूछताछ ऋणदाताओं को यह संकेत देती है कि आपको जल्दी में उधार चाहिए।',
          'इसलिए यह देखने के लिए कि कौन हाँ कहता है, एक साथ पाँच जगह आवेदन मत कीजिए। पहले प्रकाशित दरों और ऐसी पात्रता-जाँचों से प्रस्तावों की तुलना कीजिए जिनमें पूरा आवेदन नहीं लगता, फिर उन एक-दो जगह आवेदन कीजिए जो सही बैठें।',
          'अगर आवेदन ख़ारिज हो, तो कहीं और कोशिश करने से पहले कारण पूछिए। कारण — आय, पहले से चल रही किश्तें, रिपोर्ट में कोई ग़लती — यह तय करता है कि अगला आवेदन रुककर करना चाहिए या नहीं।',
          'क्रेडिट रिपोर्ट में ग़लतियाँ होती हैं: बंद ऋण अब भी खुला दिखना, समय पर हुआ भुगतान देर से दर्ज होना। हर ब्यूरो में विवाद दर्ज करने की प्रक्रिया है, और आवेदन से पहले रिकॉर्ड सुधरवाना फ़ायदेमंद है।',
          'अंत में, अगर कोई मित्र या रिश्तेदार आपसे गारंटर या सह-आवेदक बनने को कहे, तो समझिए कि उस हस्ताक्षर का अर्थ क्या है। अगर वे भुगतान बंद कर दें, तो ऋणदाता पूरी राशि आपसे वसूल सकता है, और वह ऋण आपकी अपनी क्रेडिट रिपोर्ट में भी दिखता है।',
          'गारंटर बनना कोई औपचारिकता या पल भर का एहसान नहीं है। हाँ केवल उतनी राशि के लिए कहिए जितनी आप अपने घर को नुक़सान पहुँचाए बिना ख़ुद चुका सकें।',
        ],
        pEn: [
          'Each formal loan application usually leads to an enquiry being recorded on your credit report. A few enquiries are normal; many in a short span suggest to lenders that you are urgently looking for credit.',
          'So do not apply to five lenders at once to see who says yes. Compare offers first, using published rates and eligibility checks that do not need a full application, and then apply to the one or two that fit.',
          'If an application is rejected, ask why before trying elsewhere. The reason — income, existing instalments, an error on the report — decides whether the next application should wait.',
          'Errors on credit reports do occur: a closed loan still shown as open, an on-time payment recorded as late. Every bureau has a dispute process, and getting the record corrected is worth doing before you apply.',
          'Finally, if a friend or relative asks you to be a guarantor or co-applicant, understand what that signature means. If they stop paying, the lender can recover the full amount from you, and the loan appears on your own credit report.',
          'Being a guarantor is not a formality or a favour of the moment. Agree only to an amount you could repay yourself without damaging your own household.',
        ],
      },
    ],
  },
  {
    slug: 'emergency-fund-where-to-keep',
    sections: [
      {
        hHi: 'एक परिवार का कोष, परत-दर-परत',
        hEn: 'One household’s fund, layer by layer',
        pHi: [
          'परतों वाली व्यवस्था एक परिवार के उदाहरण पर सबसे आसानी से समझ आती है। संख्याएँ केवल उदाहरण हैं; आप अपनी संख्याएँ लगाइए।',
          'मान लीजिए ज़रूरी मासिक ख़र्च — किराया, राशन, बिजली, स्कूल फ़ीस, दवाइयाँ, आना-जाना — ₹40,000 बनते हैं, और परिवार ने छह महीने का कोष तय किया है। लक्ष्य ₹2,40,000 है।',
          'पहली परत, लगभग ₹15,000: थोड़ी नक़दी घर में और बाक़ी उस रोज़मर्रा के खाते में जिसका कार्ड हमेशा साथ रहता है। अस्पताल में भर्ती की अग्रिम राशि या उसी शाम के किसी ज़रूरी टिकट के लिए पर्याप्त।',
          'दूसरी परत, लगभग ₹65,000: एक अलग बचत खाता, या तुरंत तोड़ी जा सकने वाली जमा, रोज़मर्रा वाले बैंक से अलग किसी बैंक में। यह किसी भी मुश्किल के पहले एक-दो महीनों को सँभालती है।',
          'तीसरी परत, ₹1,60,000: ₹40,000 की चार जमा, जो तीन-तीन महीने के अंतर पर परिपक्व हों। हर एक, एक महीने का ख़र्च है जो बिना कुछ तोड़े अपने-आप हाथ में आ जाता है।',
          'धीरे-धीरे बनाते समय भी क्रम यही रहे: पहले पहली परत, फिर दूसरी, फिर सीढ़ी। और पूरी व्यवस्था एक पन्ने पर लिख लीजिए — कौन-सा खाता, कौन-सा बैंक, कौन-सी परिपक्वता तिथियाँ — क्योंकि ज़रूरत के दिन किसी को खोजना नहीं पड़ना चाहिए।',
        ],
        pEn: [
          'The layered structure is easiest to understand on a single household. The figures are illustrative; put in your own.',
          'Suppose the essential monthly expenses — rent, food, electricity, school fees, medicines, travel — come to ₹40,000, and the family has settled on six months. The target is ₹2,40,000.',
          'First layer, about ₹15,000: a little cash at home and the rest in the everyday account whose card is always carried. Enough for a hospital admission deposit or an urgent ticket the same evening.',
          'Second layer, about ₹65,000: a separate savings account, or a deposit that can be broken immediately, held at a bank other than the everyday one. This carries the first month or two of any difficulty.',
          'Third layer, ₹1,60,000: four deposits of ₹40,000 each, maturing three months apart. Each is one month of expenses that arrives by itself, without breaking anything.',
          'When building it gradually, keep the same order: the first layer, then the second, then the ladder. And write the whole structure on one page — which account, which bank, which maturity dates — because on the day it is needed nobody should be searching.',
        ],
      },
      {
        hHi: 'बचत खाता, स्वीप-इन, FD या लिक्विड फ़ंड',
        hEn: 'Savings account, sweep-in, deposit or liquid fund',
        pHi: [
          'भारत में आमतौर पर चार विकल्प सामने आते हैं, और हर एक तीनों कसौटियों पर अलग-अलग हद तक खरा उतरता है।',
          'बचत खाता पहुँच और स्थिरता, दोनों पर पूरी तरह खरा है और ब्याज सबसे कम देता है। पहली परतों के लिए यही सही जगह है, और ज़रूरत के दिन इसमें कुछ तय नहीं करना पड़ता।',
          'स्वीप-इन या ऑटो-स्वीप सुविधा बचत खाते को जमा से जोड़ती है: एक तय सीमा से ऊपर की राशि जमा में चली जाती है और शेष कम पड़ने पर अपने-आप लौट आती है। इसमें पहुँच के साथ कुछ बेहतर ब्याज मिलता है, हालाँकि जुड़ी हुई जमा तोड़ने की शर्तें हर बैंक में अलग होती हैं।',
          'समय से पहले निकासी की सुविधा वाली FD स्थिर है और नेट बैंकिंग से आमतौर पर एक दिन के भीतर मिल जाती है। जल्दी तोड़ने पर लगने वाला जुर्माना देखिए, और यह भी कि क्या उसे शाखा गए बिना ऑनलाइन तोड़ा जा सकता है।',
          'लिक्विड और ओवरनाइट म्यूचुअल फ़ंड बहुत छोटी अवधि के साधनों में निवेश करते हैं। ये आमतौर पर स्थिर रहते हैं पर गारंटीड नहीं, पैसा निकालने में आमतौर पर एक कार्यदिवस लगता है, और कुछ फ़ंड सीमित राशि की तुरंत निकासी की सुविधा देते हैं। जो इन्हें समझते हैं, उनके लिए ये तीसरी परत में ठीक हो सकते हैं — पहली में कभी नहीं।',
          'बैंक जमा, जमा बीमा योजना के तहत प्रति जमाकर्ता प्रति बैंक एक सीमा तक बीमित होती है। अगर कोष उस सीमा से बड़ा है, तो उसे दो मज़बूत बैंकों में बाँटना समझदारी है — और इससे यह भी बचाव होता है कि ग़लत दिन किसी एक बैंक का ऐप या शाखा उपलब्ध न हो।',
        ],
        pEn: [
          'In India the usual candidates are four, and each passes the three tests to a different degree.',
          'A savings account passes access and stability completely and earns the least. It is the right home for the first layers, and on the day of need nothing has to be decided.',
          'A sweep-in or auto-sweep facility links the savings account to deposits: money above a set level moves into a deposit and comes back automatically when the balance runs short. It combines access with somewhat better interest, though the terms for breaking the linked deposits differ from bank to bank.',
          'A fixed deposit that allows premature withdrawal is stable and can usually be reached within a day through net banking. Check the penalty for breaking it early, and whether it can be broken online without a branch visit.',
          'Liquid and overnight mutual funds hold very short-term instruments. They are generally steady but not guaranteed, redemption usually takes a working day, and some offer instant withdrawal of a limited amount. For someone who understands them they can suit the third layer — never the first.',
          'Bank deposits are covered by the deposit insurance scheme up to a limit per depositor per bank. If the fund is larger than that limit, splitting it across two sound banks is sensible — and it also protects against one bank’s app or branch being unavailable on the wrong day.',
        ],
      },
      {
        hHi: 'अगर आप न पहुँच सकें, तो क्या परिवार पहुँच सकता है?',
        hEn: 'Can your family reach it if you cannot?',
        pHi: [
          'आपातकालीन कोष आमतौर पर एक सवाल के इर्द-गिर्द बनाया जाता है — क्या मैं इस तक जल्दी पहुँच सकता हूँ? पर कई असली आपात स्थितियाँ एक दूसरा सवाल पूछती हैं: जब मैं अस्पताल में हूँ या संपर्क से बाहर हूँ, तब क्या कोई और इस तक पहुँच सकता है?',
          'अगर कोष ऐसे खाते में है जिसे केवल आप चला सकते हैं — आपके फ़ोन, आपके पासवर्ड और आपकी उँगली के निशान से सुरक्षित — तो उत्तर "नहीं" हो सकता है, और ठीक उसी स्थिति में जिसके लिए कोष बना था।',
          'कुछ सरल व्यवस्थाएँ इसका अधिकांश हल कर देती हैं। दूसरी परत को जीवनसाथी या किसी भरोसेमंद वयस्क के साथ "आइदर ऑर सर्वाइवर" वाले संयुक्त खाते में रखिए, ताकि किसी एक के हस्ताक्षर से काम चल जाए।',
          'हर खाते और हर जमा पर नामांकन (नॉमिनी) दर्ज कीजिए। नॉमिनी रोज़मर्रा की पहुँच में मदद नहीं करता, पर सबसे बुरी स्थिति में परिवार के लिए एक कठिन प्रक्रिया को बहुत आसान बना देता है।',
          'ऊपर बताया गया एक पन्ने का नोट ऐसी जगह रखिए जहाँ परिवार उसे ढूँढ सके — बैंक, खाते का प्रकार और परिपक्वता तिथियाँ लिखी हों, पर पासवर्ड, PIN या OTP कभी नहीं। ये कहीं भी लिखे नहीं जाने चाहिए।',
          'फिर एक बार इसकी परीक्षा कीजिए। संयुक्त खाताधारक से कहिए कि वे अकेले एक छोटी राशि निकालकर देखें। किसी सामान्य दिन के दस मिनट बता देते हैं कि व्यवस्था काम करती है या नहीं — यह ज़रूरत के दिन पता चलने से कहीं बेहतर है।',
        ],
        pEn: [
          'An emergency fund is usually planned around one question — can I reach it quickly? Many real emergencies ask a different one: can somebody else reach it while I am in hospital or out of contact?',
          'If the fund sits in an account only you can operate, protected by your phone, your password and your fingerprint, the answer may be no — in precisely the situation the fund was built for.',
          'A few simple arrangements solve most of this. Hold the second layer in a joint account with your spouse or another trusted adult, operated "either or survivor", so that either signature is enough.',
          'Register nominees on every account and every deposit. A nominee does not help with day-to-day access, but if the worst happens it makes a difficult process far simpler for the family.',
          'Keep the one-page note described above where the family can find it, listing the banks, account types and maturity dates — but never passwords, PINs or one-time codes. Those should not be written down anywhere.',
          'Then test it once. Ask the joint holder to withdraw a small amount on their own. Ten minutes on an ordinary day shows whether the arrangement works, which is far better than finding out on the day it is needed.',
        ],
      },
    ],
  },
];
